import { NgModule } from "@angular/core"
import { CommonModule } from "@angular/common"
import { RouterModule, type Routes } from "@angular/router"
import { SharedModule } from "../shared/shared.module"
import { ReportListComponent } from "./components/report-list/report-list.component"
import {ReportDetailComponent} from './components/report-details/report-details.component';
import {AutoGeneratedReportsComponent} from './components/auto-generated-report/auto-generated-report.component';

const routes: Routes = [
  { path: "", component: ReportListComponent },
  { path: ":reportId", component: ReportDetailComponent },
  { path: "auto-generated", component: AutoGeneratedReportsComponent },
]

@NgModule({
  declarations: [], // Declare the component
  imports: [CommonModule, ReportListComponent,SharedModule, RouterModule.forChild(routes)],
  exports: [RouterModule],
})
export class ReportModule {}
