package com.pcd.report.model;

import lombok.AllArgsConstructor;
import lombok.Builder;
import lombok.Data;
import lombok.NoArgsConstructor;
import org.springframework.data.annotation.CreatedDate;
import org.springframework.data.annotation.Id;
import org.springframework.data.annotation.LastModifiedDate;
import org.springframework.data.mongodb.core.mapping.Document;

import java.time.LocalDateTime;
import java.util.ArrayList;
import java.util.List;
import java.util.Map;

@Document(collection = "reports")
@Data
@Builder
@NoArgsConstructor
@AllArgsConstructor
public class Report {

    @Id
    private String id;

    private String title;

    private String description;

    private String caseId;

    private String caseNumber;

    private String investigatorId;

    private String expertId;

    private String status;

    private List<Map<String, Object>> analyses = new ArrayList<>();

    private String verdict;

    private String judicialNotes;

    private List<String> imageUrls = new ArrayList<>();

    private List<String> attachmentIds = new ArrayList<>();

    private ReportType reportType;

    private String generatedBy;

    private byte[] pdfContent;

    @CreatedDate
    private LocalDateTime createdAt;

    @LastModifiedDate
    private LocalDateTime updatedAt;

    private String templateId;

    private boolean autoGenerated;

    private String reportUrl;
}
