global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: 'spring-boot-apps'
    metrics_path: '/actuator/prometheus'
    static_configs:
      - targets: ['user-service:8090', 'imageanalysis-service:8051', 'imagemanagement-service:8050', 'report-service:8053']
