spring:
  mail:
    host: smtp.gmail.com
    port: 587
    username: pcdjudge@gmail.com
    password: idoe lqso dnam tkjx
    name: FIDS
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true
  kafka:
    bootstrap-servers: localhost:9092
    consumer:
      group-id: email-service
      auto-offset-reset: earliest


server:
  port: 8668

email:
  dlq:
    topic: email-dlq