spring:
  config:
    import: optional:configserver:http://localhost:8888
  application:
    name: imageAnalysis-service
  cloud:
    config:
      fail-fast: false
      retry:
        max-attempts: 20
        initial-interval: 1500
